apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-replicaset
  namespace: jinho
spec:
# 몇대의 Pod를 띄울거냐
  replicas: 2
  selector:
  # 아래의 (match)labels은 replicaset이 관리해야 할 pod를 결정하는데 사용
    matchLabels:
      app: my-nginx
  template: 
    metadata:
    # 서비스가 바라보기 위한 label
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: jinho-service
  namespace: jinho
spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx